/*******************************************************************************
* IntelHex - class definitions                                                 *
*                                                                              *
* A class to handle the encoding and decoding of an Intel HEX format file as   *
* generated by many tool chains for embedded processors and microcontrollers.  *
*                                                                              *
********************************************************************************/

#pragma once
#include <iostream>
#include <map>
#include <list>
using namespace std;

class IntelHex
{
private:

	struct HexRecord{
		string dataLength;
		string startAddress;
		string recordType;
		string data;
		string sumCheck;
	};

	struct HexLine {
		int lineNo;
		HexRecord hexRecord;
	};


	CString fileName;
	FILE *pHexFile;
	list<HexLine> fileContent;



	bool open();
	bool formatParse(const char *src, const int lineNo);
	bool hexFormatParse(const char *src, char *dst);

public:
	IntelHex(void) { }
	IntelHex(const CString& hexFileName) {
		fileName = hexFileName;
	}

	~IntelHex(void) { 
		if (pHexFile){
			fclose(pHexFile);
		}
	}

	void parse();
	


	


};

